This repository contains a version of the PCF Developer course with the following changes:

  * Lab instructions have been ported to asciidoc (thanks Eitan)
  * It uses the common-build
  * It is self-contained as far as possible

## Using Common Build

Since it uses the common build, you must `cd` into the `build` directory and then the following ant targets are available:

  * `ant lab-docs` - builds the lab instructions as HTML and PDF in `build\lab-instructions\target\generated-docs`
  * `ant handouts` - 
  * `ant install-docs` - creates lab instructions and the handout in `build\target\pcf-developer-XXX.RELEASE` (XXX is the release id)
  * `ant install-labs` - creates a zip of the labs in `build\target\pcf-developer-XXX.RELEASE\Student Files`
  
Run `ant` on its own for a list of targets and see the [Common Build Wiki](https://github.com/pivotal-education/common-build/wiki).

## Using Gradle Build

In addition to using rhe common-build, Eitan's build cripts are retained for the present.
To generate the course as html:

----
gradle asciidoctor
----

To generate a PDF version of the course materials:

----
gradle -b build-pdf.gradle asciidoctor
----

After reviewing and modifying the `manifest.yml` file, you can publish the html version of the course contents to PCF with the following command:

----
cf push
----

At the moment, a version of this course is published to https://pcfdeveloper.cfapps.io/[this url^].

Thanks.
/ Eitan
