= Setting Up Mongo DB VM on AWS

== Context

If you are attending an Instructor-led or Live-Online course, your instructor will
do this for you.

If you are taking this course as E-Learning, you will need to do this yourself unless
you already have access to a running MongoDB system.

== Setup Mondgo DB VM

We will be using https://www.terraform.io[Terraform] (from Hashicorp) to create our VM.

You should have a file called `mongo.tf` as part of your materials.  Put
this in a convenient working directory.

Go to https://www.terraform.io, download and install the software.  Ensure that
`terraform` is on your `PATH`.

Login to your AWS account and navigate to the EC2 dashboard.  __Make sure you have
US East (N. Virginia) set as your active region__.

=== Keys and Configuration

You need a security key-pair.  If you don't have one already:

  * In the left-hand panel, click `Key Pairs`.
  * Then click `Create Key Pair` and specify your key-pair name
  * Create the key-pair and download the PEM file when prompted.
  * Copy the PEM file you have downloaded to the directory where you have
     placed the `mongo.tf` file
  * If running on Unix (MacOS/Linux) restrict access using `chmod 400 <your-key>.pem`
  * DO NOT lose this file, there is no way to recover it

The VM configuration is specified using the `mongo.tf` file that you should have
downloaded previously.  It takes a MongoDB AMI (VM template) and wraps security
around it.

The `mongo.tf` file expects certain variables to make it work.  Create a file called
`variable.tf` and copy this text into it:

```
variable "access_key" {
    default = "AWS-ACCESS-KEY"
}
    
variable "secret_key" {
    default = "AWS-SECRET-KEY"
}
    
variable "key_name" {
    default = "YOUR-KEY-PAIR-NAME"
}

variable "key_path" {
    default = "/absolute/path/to/your/PEM/file"
}

variable "region" {
    default = "us-east-1"
}
    
variable "username" {
    default = "YOUR_AMS_LOGIN_NAME"
}
```

=== Creating the VM

For full details of using Terraform, go here:
https://www.terraform.io/intro/getting-started/install.html.

Replace each of the defaults with their correct values.

Try and run your plan:

```
terraform mongo.tf plan
```

If it works, run

```
terraform mongo.tf apply
```

You may be prompted to go to AWS and purchase the VM instance you are about to create.
Once AWS is happy, come back and run `terraform mongo.tf apply` again.

Once the script has run, it finishes by telling you the static IP address of your
new VM.  This is the `MONGODB_HOST` they need for the Service Btoker lab.

Return to EC2 dashboard and view your instance.  Wait for it to finish starting up.

Select your VM, and in the Actions dropdown -> Instance Settings -> Get System Log.
Scan the log for "Setting Bitnami application password to".  See here for more
details: https://docs.bitnami.com/aws/faq/#how-to-find-application-credentials.
This is the `MONGODB_PASSWORD` needed for the lab.

=== Using the VM

This is all you need to do to finish the Service Broker Lab.

Once you have finished the lab, you can get rid of the VM by going to your AWS EC2
dashboard, selecting the MongoDB instance, and clicking `Actions` -> `Instance State` ->
`Terminate`.  The VM should stop, change to "Terminated" status and will eventually be
removed from your list of VMs (The VM will shutdown and eventually be removed from your
list of VMs (removal may not happen immediately)emoval may not happen immediately)


== Accessing Your Mongo VM Remotely

If you wish you can access MongoDB and see what you have setup in the lab.

You can SSH into the VM using your private key, the `bitnami` username and the public
IP address or hostname of your VM.

For example:

[source.terminal]
----
ssh -i ~/.ssh/my-key-pair.pem bitnami@53.91.185.0
----

For more information refer to the 
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html[Amazon Reference Documentation^]


=== Managing MongoDB

*Start MongoDB*

[source.terminal]
----
sudo /opt/bitnami/ctlscript.sh start
----

*Stop MongoDB*

[source.terminal]
----
sudo /opt/bitnami/ctlscript.sh stop
----

*Restart MongoDB*

[source.terminal]
----
sudo /opt/bitnami/ctlscript.sh restart
----

See https://docs.bitnami.com/aws/infrastructure/mongodb/[here^] for more information.

=== The Mongo Shell

The `mongo` shell is also loaded on the VM.  It can be accessed in the terminal by
doing the following:

[source.terminal]
----
mongo
----

Once in the shell, you'll have to authenticate.  The username is `root`, and the
password is the one you previously obtained from the VM system log:

[source,bash]
----
use admin
db.auth('root', '<password>')
----

For more information refer to the 
https://docs.mongodb.org/manual/mongo/[Mongo Shell Reference^]



