= Manifest
Eitan Suez <esuez@pivotal.io>
v0.1, 2017:  GCP-specific Lab Instructions
:linkcss:
:docinfo: shared
:toc: left
:sectnums:
:linkattrs:
:icons: font
:source-highlighter: highlightjs
:imagesdir: images
:experimental:


_Estimated Time: 10 minutes_

== Preface

You can imagine how tedious things would be if we had to repeatedly pass a handful of command arguments to the cf cli each time we push an application.  There's a better way:  application manifests allow you to consolidate into a single file all of our application's deployment metadata, including the application name, memory, path, hostname, and much more.  We can associate services and environment variables to our application in a single manifest file.

Don't forget to take the time to read through the excellent documentation on manifests that's referenced below.  There are lots of manifest file attributes you'll want to learn about.  If you're new to yaml, take a little time to familiarize yourself with the syntax.

In this lab you'll reverse-engineer an application manifest file from one of the running applications you deployed in the last lab.  That's a pretty convenient feature.

== Exercises

=== Create an application manifest

. Read about https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html[application manifests^]

. Change directories to the `attendee-service` application.
+
[source.terminal]
.Example:
----
cd ~/pivotal-cloud-foundry-developer-workshop/attendee-service/
----

. Generate a manifest.
+
[source.terminal]
----
cf create-app-manifest attendee-service -p ./manifest.yml
----

. Edit the manifest.
+
* Increase the `instances` to `2`.
* Add a manifest attribute entry to set the https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#path[path^] to the application's artifact (`attendee-service-0.1.jar`).

. Push `attendee-service`.
+
[source.terminal]
----
cf push
----

. Confirm the `attendee-service` is running and the latest push parameters are reflected.
+
[source.terminal]
----
cf app attendee-service
----

==== Questions

* Assuming you have application running with a bound service (MySQL).  You `push` the application again with a manifest, but said service is not specified in the manifest.  Is the service still bound to the application?
* What are some `cf` commands that don't have to be explicitly made when using manifests?
* Why did the `create-app-manifest` command not write the `path` attribute for me?  In other words, why did I have to specify it manually?

=== Cleanup

. Edit the manifest.

* Decrease the `instances` to `1`

. Push `attendee-service`.
+
[source.terminal]
----
cf push
----
